# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Guide du surfeur de Loire Atlantique
email: lucas.lestandi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ce site a pour but de partager les connaissances que j'ai acquise autour du surf et des spots de l'ouest de la France.
baseurl: surf
url: https://llestandi.github.io
github_username: llestandi
minimal_mistakes_skin: air
search: true
locale: "fr"


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Lucas Lestandi"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Salut ! C'est Lucas je surf depuis 2017, j'ai arpenté des surf dans bien des endroit et j'ai envie de partager ce que j'ai appris sur les spots et les vagues. Pour la technique on repassera et puis, il y a youtube. Membre de l'Association Loire Atlantique de surf depuis 2022. Je suis Maitre de Conférence à l'école Centrale de Nantes spécialiste de la simulation numérique pour la mécanique ce qui explique une passion pour la théorie et la modélisation que je m'efforcerait de partager dans les différents guide qui viendrons peupler cette page.s"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://llestandi.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/llestandi"
    

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

    # _surf_posts
  - scope:
      path: ""
      type: surf_spots
    values:
      layout: single
      author_profile: true
      share: true
  
    # __beginner_guide
  - scope:
      path: ""
      type: beginner_guide
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# TODO Check whether this is correct
collections:
  surf_spots:
    output: True
    permalink: /:collection/:path/
  beginner_guide:
    output: True